TrainingArguments:
  num_train_epochs: 0
  warmup_steps: 800
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 16
  weight_decay: 0.01
  logging_steps: 100
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 500
  save_steps: 500
  save_total_limit: 2
  load_best_model_at_end: True